import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import ThemeProvider from "../context/ThemeProvider";
import RenderConditionalLayout from "../components/conditional-rendering/RenderConditionalLayout";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "SaaS Landing Page Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider>
          <RenderConditionalLayout>
            <Navbar />
          </RenderConditionalLayout>
          {children}
          <RenderConditionalLayout>
            <Footer />
          </RenderConditionalLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
